version: '3.8'

include:
  - compose.db.yml

services:
  app: 
    image: gym-register-api:latest
    build: 
      context: .
      args:
        - RUST_VERSION=${RUST_VERSION}
    env_file:
      - .env
    ports:
      - "${CONTAINER_PORT}:${APP_PORT}"
    networks:
      - gym-register-db
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: .
